services:
  - type: web
    name: bcut-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 8080
      - key: UNLEASHNFTS
        sync: false
